import './shared_scss/main.scss';
import './components/events-list/events-list';
import './services/apiService.js';
import './components/modal/modal';
import './components/scroll-up/scroll_up';
import './components/theme-switch/theme-switch';
import './components/authentication/auth';
import './components/modal-timer/modal-timer';
import './components/developer-card/developers-list';
