export default [
    {
        nameDev: 'Andrey Cherniak',
        image: 'images/dev-card-foto/Cherniak-foto.jpg',
        // image: 'https://i.ibb.co/8zbQ8zb/Cherniak-foto.jpg',
        github: 'https://github.com/ChristianRC007',
        linkedin: 'https://www.linkedin.com/in/andrei-cherniak-294666210/',
    },
    {
        nameDev: 'Anna Myzika',
        image: 'images/dev-card-foto/Myzika-foto.jpg',
        // image: 'https://i.ibb.co/s9XjBtm/Myzika-foto.jpg',
        github: 'https://github.com/AnnaMyzika',
        linkedin: 'https://www.linkedin.com/feed/',
    },
    {
        nameDev: 'Artem Smirnov',
        image: 'images/dev-card-foto/Smirnov-foto.jpg',
        // image: 'https://i.ibb.co/7p3rf2g/Smirnov-foto.png',
        github: 'https://github.com/Art-Smirnov',
        linkedin: 'https://www.linkedin.com/feed/',
    },
     {
         nameDev: 'Ayta Arylova',
         image: 'images/dev-card-foto/Arylova-foto.jpg',
        // image: 'https://i.ibb.co/cTjbKV9/Arylova-foto.jpg',
        github: 'https://github.com/AytaAA',
        linkedin: 'https://www.linkedin.com/in/ayta-arylova-45406470/',
    },
      {
          nameDev: 'Dmitriy Hordyna',
          image: 'images/dev-card-foto/Hordyna-foto.jpg',
        // image: 'https://i.ibb.co/KsTLTnQ/Hordyna-foto.jpg',
        github: 'https://github.com/DmitryHordyna',
        linkedin: 'https://www.linkedin.com/feed/',
    },
       {
           nameDev: 'Irina Selina',
           image: 'images/dev-card-foto/Selina-foto.jpg',
        // image: 'https://i.ibb.co/ZdJSPq7/Selina-foto.jpg',
        github: 'https://github.com/IrinaSelina',
        linkedin: 'https://www.linkedin.com/in/irina-selina-9857541b6/',
    },
        {
            nameDev: 'Lesya Stulkivska',
            image: 'images/dev-card-foto/Stulkivska-foto.jpg',
        // image: 'https://i.ibb.co/58xzjBF/Stulkivska-foto.jpg',
        github: 'https://github.com/Legrito',
        linkedin: 'https://www.linkedin.com/in/lesya-stulkivska/',
    },
    {
        nameDev: 'Nika Nyrkova',
        image: 'images/dev-card-foto/Nyrkova-foto.jpg',
        // image: 'https://i.ibb.co/mbxF7MG/Nyrkova-foto.jpg',
        github: 'https://github.com/NikaNyrkova',
        linkedin: 'https://www.linkedin.com/feed/',
    },
   
    {
        nameDev: 'Oleksii Bohatyrenko',
        image: 'images/dev-card-foto/Bohatyrenko-foto.jpg',
        // image: 'https://i.ibb.co/ZVhjH78/Bohatyrenko-foto.jpg',
        github: 'https://github.com/Bohatyrenko',
        linkedin: 'https://www.linkedin.com/feed/',
    },
];
